### ISSUE TITLE
ISSUE: Adding large files to gyre/github repo

### ISSUE THREAD

**Issue by andrewfagerheim** [ocean-transport/argo-intern#11]
After reading the Steinberg paper, I looked at [this database](http://mixedlayer.ucsd.edu/) of calculated mixed layer depths for every profile collected by Argo -- which at the very least would be interesting to look at, and may be very useful down the road. However, the netcdf file is very large (300+ MB) and file size limits for uploading files to Gyre and GitHub are much smaller (15MB and 25MB). I also tried cloning this repo to my laptop, adding the file, then pushing the changes back to my repo, but it said the file size limit is 100MB.

**Comment by dhruvbalwada** [comment]
Maybe add .nc files to your .gitignore files (or save data in some other place, which does not sync with github). You don't want to be uploading datafiles to the github.

**Comment by andrewfagerheim** [comment]
Jupyter Notebook in Gyre won't let you move large files over through the web interface, so here are the steps for going around that:
- open a terminal on your computer and type: `scp local_file_path amf2288@gyre.ldeo.columbia.edu:/home.ufs/amf2288/destination_path`
- it should ask you for your password -- enter it here, and it should copy the file to the specified destination_path

**Comment by andrewfagerheim** [comment]
Jupyter Notebook in Gyre won't let you move large files over through the web interface, so here are the steps for going around that:
- open a terminal on your computer and type: `scp local_file_path amf2288@gyre.ldeo.columbia.edu:/home.ufs/amf2288/destination_path`
- it should ask you for your password -- enter it here, and it should copy the file to the specified destination_path

The .nc file with MLD for all argo profiles is now in my argo-intern directory! Closing this issue since this is resolved.
