### ISSUE TITLE
Summer 2022: Administrative Tasks

### ISSUE THREAD

**Issue by andrewfagerheim** [ocean-transport/argo-intern#2]
3 June 2022
- [x] Gain access to Gyre server (email Ryan and LDEOIT)
- [x] Request access to Pangeo cloud
- [x] Sign up for an ORCid
- [x] Create a GitHub repo and add a README file
- [x] Organize Google Drive notes into issues here

**Comment by andrewfagerheim** [comment]
6 June 2022

- [x] Gain access to group Google Calendar for meetings @jbusecke 
- [x] Create reminder to send Dhruv and Julius next week's schedule either Friday or Saturday each week
- [x] Add instructions and resources for SSH to References
- [x] Ensure all packages are installed in Gyre environment
- [x] Add notes of meeting with Julius to Roadmap
- [x] Check in with Pangeo Cloud and let Julius know if you still don't have access by tomorrow morning

**Comment by andrewfagerheim** [comment]
> 3 June 2022

> * [x]  Sign up for an ORCiD

ORCiD: 0000-0002-3230-512X

> * [x] Organize Google Drive notes into issues here

I'm putting meeting notes under #1, including the date at the top, and tagging whoever I was in the meeting with

**Comment by jbusecke** [comment]
[Instructions for the VPN](https://ldeo-it.ldeo.columbia.edu/content/vpn-virtual-private-network)

**Comment by andrewfagerheim** [comment]
7 June 2022

- [x] Get monitor/desk setup
- [ ] Connect SSH key to Pangeo Cloud
- [ ] Create draft of presentation for first focusing session and share with Julius and Dhruv
- [ ] Is there a way to connect GitHub to presentation program to include issues/files/plots?

**Comment by jbusecke** [comment]
>  Is there a way to connect GitHub to presentation program to include issues/files/plots?

I am not sure I understand exactly what you mean here. You can just paste links to the issues etc in powerpoint/google slides. Or are you looking to embed things?

**Comment by andrewfagerheim** [comment]
Closing issue from this summer
