### ISSUE TITLE
ISSUE: Mapping with cartopy

### ISSUE THREAD

**Issue by andrewfagerheim** [ocean-transport/argo-intern#5]
8 June 2022

When I graphed the glider path using cartopy the results seemed both logically inconsistent and in the wrong place based on what Dhruv and I had discussed. There seemed to be two problems:

- Dhruv said the glider path was in the Indian Ocean off the eastern cost of Africa, yet the plot placed it off the western coast of Africa at essentially 0S 0E
- The scale of the path seemed far too small, at roughly 0.0006S 0.0003E

![image](https://user-images.githubusercontent.com/106624836/172873292-2776d546-a645-4bcb-80c1-9a84d2680ce5.png)

**Comment by rabernat** [comment]
You may need to provide the `transform` argument to `plot`. See https://earth-env-data-science.github.io/lectures/mapping_cartopy.html#adding-data-to-the-map

**Comment by jbusecke** [comment]
Can you plot the longitude vs latitude without using the map projection `plt.plot(lon,lat)`? That will enable us to narrow down if the problem is with the data or is due to the projection details.

**Comment by andrewfagerheim** [comment]
8 June 2022

@dhruvbalwada first said that I flipped the x and y axes: x should be longitude and y should be latitude. This correctly oriented the glider path (a problem I didn't know existed) but didn't solve either of the two problems outlined above.
![image](https://user-images.githubusercontent.com/106624836/172874020-433c4101-85a1-4f9a-9c7d-909fe5afb30e.png)

**Comment by andrewfagerheim** [comment]
9 June 2022

@dhruvbalwada then said it was probably an issue with the projection I was using. So I switched from using the Robinson projection to the Platte Carree projection and this seemed to fix both issues. Both the scale and location seem much more reasonable.


![image (1)](https://user-images.githubusercontent.com/106624836/172874432-16b6b147-0d7f-435a-86d7-8c7b0e30ee17.png)

**Comment by rabernat** [comment]
In general, you should always specify `transform=ccrs.PlateCarree()` in your call to `plot` if you data are specified in lat lon. That will allow you to use any projection. Try it with Robinson and see if it works.

**Comment by andrewfagerheim** [comment]
Yes that worked, thanks for the help!! I think that can close this issue
![image](https://user-images.githubusercontent.com/106624836/172892399-8a1b8ab0-82ee-4805-870a-b2d49213ff1c.png)
