### ISSUE TITLE
Timekeeping

### ISSUE THREAD

**Issue by andrewfagerheim** [ocean-transport/argo-intern#9]
This issue is to keep track of hours spent on the project for reporting on the bi-weekly timesheet. Times must be reported in half hour increments and a half hour break must be taken after 5hrs of work. Use the link below to see when timesheets and approvals are due.

https://drive.google.com/file/d/1zDQTndVHqnrC-OiPY1er2lRaZYPkYvqM/view?usp=sharing

**Comment by andrewfagerheim** [comment]
Week of 11/20
-

Monday: 9AM-11:45AM (2.75 hours)
Wednesday: 2:30PM-3:45PM (1.25 hours)

**Comment by andrewfagerheim** [comment]
Week of 11/27
-

Wednesday: 2:30PM-3:30PM, 9PM-10PM (2 hours)
Thursday: 9:30AM-11:15AM (1.75 hours)
Friday: 9AM-12PM, 12:30PM-5PM (7.5 hours)

**Comment by andrewfagerheim** [comment]
Week of 12/4
-
Monday: 2:45PM-6:45PM (4 hours)
Thursday: 10PM-11:30PM (1.5 hours)
Friday: 10AM-1PM, 1:30PM-4:30PM (6 hours)

**Comment by andrewfagerheim** [comment]
Week of 12/11
-
Monday:  11AM-12:30PM, 4PM-6PM (3.5 hours)
Tuesday: 11AM-12:30PM (1.5 hours)
Wednesday: 10AM-12PM (2 hours)
Thursday: 10AM-12PM (2 hours)
Friday: 10AM-11AM (1 hour)

**Comment by dhruvbalwada** [comment]
You should count time you are spending in the meeting towards your hours, atleast max out to the 10 hours by counting time you spent at poster+ attending talks.

**Comment by andrewfagerheim** [comment]
Week of 5/15
-
Mon: 4PM - 7:30PM (3.5 hours)
Tue : 11:30AM - 7PM (7 hours)
Wed: 9AM - 12:30PM, 1PM - 6PM (8.5 hours)
Thu : 9AM - 12:30PM, 1PM - 6PM (8.5 hours)
Fri  :  9AM - 12PM, 12:30PM - 5PM (7.5 hours)

THIS WEEK: 35 hours

**25 hours paid from the Climate School grant. Will only work 10 hours next week to recoup the remaining 10.

**Comment by andrewfagerheim** [comment]
Timesheet Issues:
-

- I only have 25 hours remaining on the CCS grant, but I will have worked 30-35 hours by the end of this week. I haven't gotten an answer to my question about if a paycheck can come from two difference sources (ie if the CCS grant could pay for 25 hours and Ryan's make up the remainder.)
- More pressingly, Yana just told me that my working cap until the end of May is 20 hours/week (which Monica/Dante didn't tell me when I asked about starting full time in May) so it's unclear how I'm going to be paid for the hours I've worked so far anyway. 
- If Monica is here in person today, I'll try to meet with her and see if she can help think through a solution.
- My solution: Say I worked 20 hours last week and 20 hours this week, that makes up for all the time so far at least. But this still runs into the problem of half the money would need to come from CCS and the other half from Ryan.


RESOLUTION: I used up the 25 hours from the Climate School grant, meaning I have 10 hours of work remaining I haven't been paid for. Next week I will put 20 hours on the clock from Ryan's grants but only work 10. Then I'll be caught up.

**Comment by andrewfagerheim** [comment]
Week of 5/22
-

Tue: 12PM - 2PM (2 hours)

THIS WEEK: 2 hours


Week of 5/29
-

Tue: 10AM - 12PM (2 hours)
Wed: 11:30AM - 6:30PM (7 hours)
Thu: 11:30PM - 6:30PM (7 hours)
Fri: 9AM - 12PM, 12:30PM - 5:30PM (8 hours)

THIS WEEK: 24 hours

FOR THE TIMESHEET: 16 hours for the week of 5/22 (10 from the week of 5/15, 2 from the week of 5/29) and 20 hours for the week of 5/29

**Comment by andrewfagerheim** [comment]
Week of 6/5
-

Mon: 9:30AM - 12PM, 12:30PM - 5PM (7 hours)
Tue: 10AM - 12PM, 12:30PM - 4PM (5.5 hours)
Wed: 9AM - 12PM, 12:30PM - 5PM (7.5 hours)
Thu: 11AM - 12PM, 12:30PM - 6:30PM (7 hours)
Fri: 9AM - 12PM, 12:30PM - 5PM (7.5 hours)

### THIS WEEK: 34.5 hours


Week of 6/12
-

Mon: 9AM - 12PM, 1:30PM - 5PM (6.5 hours)
Tue: 10AM - 1PM, 2PM - 6PM (7 hours)
Wed: 9AM - 12PM, 12:30PM - 5PM (7.5 hours)
Thu: 10AM - 1PM, 1:30PM - 6PM (7.5 hours)
Fri: 9AM - 12PM, 12:30PM - 5PM (7.5 hours)

### THIS WEEK: 36 hours

**Comment by andrewfagerheim** [comment]
Week of 6/19
-

Mon: 
Tue: 10AM - 1PM, 1:30PM - 6PM (7.5 hours)
Wed: 9AM - 12PM, 12:30PM - 6PM (8.5 hours)
Thu: 9:30AM - 1PM, 1:30PM - 2:30PM (4.5 hours)
Fri:

### THIS WEEK: 20.5 hours

Week of 6/26
-

Mon: 12PM - 6PM (6 hours)
Tue: 10AM - 1:30PM, 3PM - 6:30PM (7 hours)
Wed: 10AM - 12PM, 12:30 - 6PM (7.5 hours)
Thu: 9:30AM - 12PM, 12:30PM - 5:30PM (7.5 hours)
Fri: 9AM - 12PM, 12:30PM - 5:30PM (8 hours)

### THIS WEEK: 36 hours

**Comment by andrewfagerheim** [comment]
Week of 7/3
-

Mon:
Tue: 10AM - 12PM, 12:30PM - 5:30PM (7 hours)
Wed: 9:30AM - 12:30PM, 1PM - 6PM (8 hours)
Thu: 10AM - 1PM, 1:30PM - 6:00PM (7.5 hours)
Fri: 9AM - 12PM, 12:30PM - 3PM, 5PM - 6:30PM (7 hours)

### THIS WEEK: 29.5 hours

Week of 7/10
-

Mon: 9AM - 12PM, 12:30PM - 6PM (8.5 hours)
Tue: 10AM - 11:30AM, 1:30PM - 6PM (6 hours)
Wed: 10:30AM - 12PM, 12:30PM - 3:30PM (4.5 hours)
Thu:
Fri:

### THIS WEEK: 19 hours

**Comment by andrewfagerheim** [comment]
Week of 7/17
-

### THIS WEEK: 0 hours

Week of 7/24
-

Mon: 9AM - 12PM, 12:30PM - 5:30PM (8 hours)
Tue: 9:30AM - 12:30PM, 1PM - 6PM (8 hours)
Wed: 9:30AM - 12:30PM, 1PM - 5PM (7 hours)
Thu: 9:30AM - 12:30PM, 1PM - 6:30PM (8.5 hours)
Fri: 9AM - 12PM, 12:30PM - 5:30PM (8 hours)

### THIS WEEK: 39.5 hours

**Comment by andrewfagerheim** [comment]
Week of 7/31
-

Mon: 10AM - 12pm, 12:30PM - 6:00PM (7 hours)
Tue: 10AM - 12PM, 12:30PM - 6:00PM (7 hours)
Wed: 10AM - 12PM, 3PM - 7PM (6 hours)
Thu: 9:00AM - 12:00PM, 12:30PM - 6:30PM (9 hours)
Fri: 9AM - 12PM, 12:30PM - 6:30PM (9 hours)

### THIS WEEK: 38 hours

Week of 8/7
-

Mon: 8AM - 9AM, 9PM - 11PM (3 hours)
Tue:
Wed:
Thu:
Fri:

### THIS WEEK: 3 hours

**Comment by andrewfagerheim** [comment]
Week of 8/14
-

### THIS WEEK: 0 hours

Week of 8/21
-
Mon:
Tue:
Wed: 7PM - 9PM (2 hours)
Thu: 11AM - 1PM, 1:30PM - 8PM (8.5 hours)
Fri: 9AM - 1PM, 1:30PM - 6:30PM (9 hours)

### THIS WEEK: 19.5 hours

**Comment by andrewfagerheim** [comment]
Week of 8/28
-
Mon: 10AM - 12PM, 12:30PM - 7:30PM (9 hours)
Tue:  10AM - 12PM, 12:30PM - 4:30PM, 5:30PM - 8:30PM (9 hours)
Wed: 9AM - 1PM, 1:30PM - 5:30PM (8 hours)
Thu: 9:30AM - 12:30PM, 1PM - 6PM (8 hours)
Fri:

### THIS WEEK: 34 hours

Week of 9/4
-
Mon:
Tue: 1:30PM - 3:30PM (2 hours)
Wed: 
Thu: 10AM - 12PM, 12:30PM - 5:30PM (7 hours)
Fri: 8:30AM - 12:30PM, 1PM - 5PM (8 hours)

### THIS WEEK: 17 hours

**Comment by andrewfagerheim** [comment]
[9/22] 10AM - 12PM, 12:30PM - 5:30PM (7 hours)

### THIS WEEK: 7 hours

**Comment by andrewfagerheim** [comment]
[10/6] 9AM - 12PM, 12:30PM - 5:30PM (8 hours)

### THIS WEEK: 8 hours

**Comment by andrewfagerheim** [comment]
[10/13] (_ hours)
[10/20] (_ hours)

### THIS PERIOD: __ hours

**Comment by andrewfagerheim** [comment]
[10/25] 12PM - 4PM (4 hours)
[10/26] 3PM - 5:30PM (2.5 hours)
[10/27] 9AM - 12PM, 12:30PM - 2:30PM (5 hours)

### THIS WEEK: 11.5 hours

[11/2] ?
[11/3] ?

### THIS WEEK: ? hours

**Comment by andrewfagerheim** [comment]
[11/9]   3PM - 6PM (3 hours)
[11/10] 9AM - 12PM, 12:30PM - 5:30PM (8 hours)

### THIS WEEK: 11 hours

[11/16] ?
[11/17] ?

### THIS WEEK: ? hours

**Comment by andrewfagerheim** [comment]
Now I have an annual stipend 
![image](https://github.com/user-attachments/assets/26e83f2d-ad20-40b5-a847-d097367cd39d)
